spring:
  h2:
    console: true

  jpa:
    show-sql: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testdb
    username: sa
    password: