spring:
  profiles:
    active: db
  redis:
    host: localhost
    port: 6379
  oauth:
    apple:
      client_id: ${OAUTH_APPLE_CLIENT_ID}
      kid: ${OAUTH_APPLE_KID}
      secret: ${OAUTH_APPLE_SECRET}
      bundle: ${OAUTH_APPLE_BUNDLE}


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
